#!/bin/bash
SOURCE=./node_modules/mathjax
UNPACKED=$SOURCE/unpacked

rm -Rf fonts
rm -Rf config
rm -Rf extensions
rm -Rf jax
rm LICENSE
rm MathJax.js

# copy LICENSE
cp $SOURCE/LICENSE .

# copy fonts
mkdir -p fonts/HTML-CSS
cp -R $SOURCE/fonts/HTML-CSS/TeX fonts/HTML-CSS

# copy config
mkdir config
cp $UNPACKED/config/default.js config
cp $UNPACKED/config/TeX-AMS_CHTML-full.js config
cp $UNPACKED/config/TeX-AMS_CHTML.js config
cp $UNPACKED/config/TeX-AMS_SVG-full.js config
cp $UNPACKED/config/TeX-AMS_SVG.js config

# copy extensions
mkdir extensions
cp $UNPACKED/extensions/*.js extensions
cp -R $UNPACKED/extensions/TeX extensions

# copy jax
mkdir jax
cp -R $UNPACKED/jax/element jax

# copy jax/input
mkdir jax/input
cp -R $UNPACKED/jax/input/TeX jax/input

# copy jax/output
mkdir jax/output
cp -R $UNPACKED/jax/output/CommonHTML jax/output

# copy jax/output/SVG
mkdir jax/output/SVG
cp $UNPACKED/jax/output/SVG/*.js jax/output/SVG
cp -R $UNPACKED/jax/output/SVG/autoload jax/output/SVG

# copy jax/output/SVG/fonts
mkdir jax/output/SVG/fonts
cp -R $UNPACKED/jax/output/SVG/fonts/STIX-Web jax/output/SVG/fonts

# copy the main script
cp $UNPACKED/MathJax.js .

# change ths BASE.isPacked value
sed -i '' 's|^// MathJax\.isPacked = true|MathJax\.isPacked = true|' MathJax.js